# ASP.NET Core (.NET Core) with Azure Pipelines
# Starter template
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master  

pool:
  vmImage: 'ubuntu-latest'  

variables:
  buildConfiguration: 'Release'
  azureWebAppServiceName: 'your-web-app-name'  # Replace with your Azure Web App name
  dotnetSdkVersion: '8.0.x'  # Replace with your desired .NET Core SDK version

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: sdk
    version: ${{ variables.dotnetSdkVersion }}
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

